-- PostgreSQL schema for FTMS (Supabase)
-- Run this file in Supabase SQL Editor or apply it via Supabase MCP migration.

-- USERS TABLE: Stores all users including admin, central bank, commercial bank, importers, exporters
CREATE TABLE IF NOT EXISTS public.ftms_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL, -- stored as BCrypt hash, never plain text
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'CENTRAL_BANK', 'COMMERCIAL_BANK', 'IMPORTER', 'EXPORTER', 'EXCHANGER')),
    account_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (account_status IN ('PENDING', 'APPROVED', 'REJECTED')), -- Account activation by admin before user can login
    kyc_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (kyc_status IN ('PENDING', 'APPROVED', 'REJECTED')), -- KYC verification for transactions
    role_selected BOOLEAN NOT NULL DEFAULT FALSE,
    city VARCHAR(100),
    address TEXT,
    phone VARCHAR(20) NOT NULL, -- now mandatory
    bank_name VARCHAR(100) NOT NULL, -- MANDATORY: commercial bank linked to user
    account_number VARCHAR(50) NOT NULL, -- MANDATORY: bank account number
    swift_code VARCHAR(20) NOT NULL, -- MANDATORY: for international transfers
    ifsc_code VARCHAR(20) NOT NULL, -- MANDATORY: for domestic transfers
    passport_data TEXT, -- Base64 encoded passport image
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TRANSACTIONS TABLE: Every forex transaction is recorded here
CREATE TABLE IF NOT EXISTS public.ftms_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.ftms_users(id) ON DELETE CASCADE, -- who initiated this transaction
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('IMPORT', 'EXPORT', 'EXCHANGE')),
    from_currency VARCHAR(10) NOT NULL, -- e.g. INR
    to_currency VARCHAR(10) NOT NULL, -- e.g. USD
    from_amount NUMERIC(15, 2) NOT NULL, -- amount user is sending
    bridge_currency VARCHAR(10) DEFAULT 'USD', -- USD as bridge currency for all conversions
    bridge_amount NUMERIC(15, 2), -- amount in USD after step 1 conversion
    to_amount NUMERIC(15, 2), -- final amount user will receive
    bank_charges NUMERIC(15, 2) DEFAULT 15.00, -- charge in USD for SWIFT/bank processing (can be in other currencies as well)
    exchange_rate NUMERIC(15, 6), -- rate used at time of transaction
    purpose TEXT, -- reason: import payment to XYZ
    beneficiary_name VARCHAR(100),
    beneficiary_bank VARCHAR(100),
    beneficiary_swift VARCHAR(20),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_CENTRAL_BANK' CHECK (
        status IN (
            'PENDING_CENTRAL_BANK',
            'APPROVED_BY_CENTRAL_BANK',
            'REJECTED_BY_CENTRAL_BANK',
            'VERIFIED_BY_BANK',
            'COMPLETED',
            'FAILED'
        )
    ),
    central_bank_approved_by BIGINT, -- user id of central bank officer who approved
    bank_verified_by BIGINT, -- user id of bank officer who verified
    rejection_reason TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ftms_transactions_user_id ON public.ftms_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_ftms_transactions_status ON public.ftms_transactions(status);

-- EXCHANGE RATES TABLE: For storing fetched or manually set rates
CREATE TABLE IF NOT EXISTS public.ftms_exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(10) NOT NULL, -- USD
    target_currency VARCHAR(10) NOT NULL, -- INR
    rate NUMERIC(15, 6) NOT NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'API' CHECK (source IN ('API', 'CENTRAL_BANK_MANUAL')),
    fetched_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ftms_exchange_rates_pair ON public.ftms_exchange_rates(base_currency, target_currency);
CREATE INDEX IF NOT EXISTS idx_ftms_exchange_rates_fetched_at ON public.ftms_exchange_rates(fetched_at);

-- Insert default non-user/system role logins (password is BCrypt of Admin@123)
INSERT INTO public.ftms_users (full_name, email, password, role, account_status, kyc_status, phone, bank_name, account_number, swift_code, ifsc_code, role_selected)
VALUES
    ('System Admin', 'admin@ftms.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lmmG', 'ADMIN', 'APPROVED', 'APPROVED', '+91-1111111111', 'Admin Bank', '1000000001', 'ADMNINBB', 'ADMIN0001', TRUE),
    ('Central Bank Officer', 'central@ftms.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lmmG', 'CENTRAL_BANK', 'APPROVED', 'APPROVED', '+91-2222222222', 'Central Bank', '2000000002', 'CNTRLNBB', 'CNTRL0002', TRUE),
    ('Commercial Bank Officer', 'bank@ftms.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lmmG', 'COMMERCIAL_BANK', 'APPROVED', 'APPROVED', '+91-3333333333', 'Commercial Bank', '3000000003', 'COMMNBB', 'COMM0003', TRUE),
    ('Importer Demo', 'importer@ftms.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lmmG', 'IMPORTER', 'APPROVED', 'APPROVED', '+91-4444444444', 'HDFC Bank', '4000000004', 'HDFCINBB', 'HDFC0004', TRUE),
    ('Exporter Demo', 'exporter@ftms.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lmmG', 'EXPORTER', 'APPROVED', 'PENDING', '+91-5555555555', 'ICICI Bank', '5000000005', 'ICICIIN', 'ICICI0005', TRUE),
    ('Exchanger Demo', 'exchanger@ftms.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lmmG', 'EXCHANGER', 'APPROVED', 'APPROVED', '+91-6666666666', 'Axis Bank', '6000000006', 'AXISINBB', 'AXIS0006', TRUE)
ON CONFLICT (email) DO NOTHING;
-- All default passwords are Admin@123

-- Supabase security hardening for public schema exposure
ALTER TABLE public.ftms_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ftms_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ftms_exchange_rates ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ftms_users FROM anon, authenticated;
REVOKE ALL ON TABLE public.ftms_transactions FROM anon, authenticated;
REVOKE ALL ON TABLE public.ftms_exchange_rates FROM anon, authenticated;
