services:
  - type: web
    name: forex-system-backend
    runtime: docker
    rootDir: forex-system-3tier/backend
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
